### ISSUE TITLE
Suggestions for Community Cad

### ISSUE THREAD

**Issue by Nmiller11126** [CommunityCAD/CommunityCAD#47]
### Type of Suggestion

CAD

### Describe the feature

Maybe a place where how many tickets, arrests, and warrants have been issued or executed that way supervisors can keep track of officers doing their duties
--
A end of shift report that auto populates the calls that you have responded to or created 
--
A section showing warrant tracking and expiration dates
--
Certainly something that could be feasible down the road but a in-game UI often times I've experienced players complain about online based cad systems because they don't have two monitors (which really if your playing fivem as a officer you need but hey)

### How would this improve RP

I believe these are reasons as to how this could improve Roleplay

Tracking Tickets, Arrests, and Warrants:
Roleplay Immersion: By keeping a record of tickets issued, arrests made, and warrants executed, the server creates a more realistic environment. Officers can refer to their own history and demonstrate consistency in their roleplay actions.
Supervisor Oversight: Supervisors can monitor officers’ performance by reviewing their activity logs. This ensures that officers are actively engaging in their duties and adhering to roleplay standards.
Incentivizes Roleplay: Officers may strive to improve their performance, knowing that their actions are being tracked. It encourages them to interact with citizens, enforce laws, and contribute to the server’s overall roleplay quality.

End-of-Shift Reports:
Efficiency: An auto-populated end-of-shift report streamlines administrative tasks. Officers don’t need to manually compile their activities; the system does it for them.
Comprehensive Documentation: The report captures all incidents an officer responded to or created during their shift. This documentation is valuable for future reference, investigations, and roleplay continuity.
Roleplay Continuity: Officers can seamlessly transition between shifts, as the report provides a summary of ongoing incidents and unresolved cases.

Warrant Tracking and Expiration Dates:
Realism: Including warrant tracking adds authenticity to law enforcement roleplay. In real life, officers actively search for individuals with active warrants.
Timely Action: Officers can prioritize serving warrants based on expiration dates. This ensures that wanted individuals are apprehended promptly.
Roleplay Opportunities: Serving warrants can lead to exciting roleplay scenarios, such as stakeouts, pursuits, and negotiations.
Considerations for In-Game UI vs. Online-Based CAD:

I believe a in-game Ui would certainly help community Cad grow as many players often don't have two screens and if the constantly have to switch back and forth they could miss something important that is happening right in front of them in that game absolutely diminishing the scene I believe it is imperative to expand in this way as a business stand point and as a RP server as well 

and Resource or something to connect the database to your cad system

### Would this help all communities

Absolutely, the features we’ve discussed can be incredibly beneficial for all roleplay communities. Here’s why:

Enhanced Immersion: Features like tracking tickets, arrests, and warrants, as well as end-of-shift reports, add a layer of realism that can deeply immerse players in their roles.

Increased Engagement: When players see that their actions are being tracked and have consequences, they’re likely to be more engaged and invested in the roleplay.

Better Accountability: With detailed records and reports, players are held accountable for their actions, which can lead to a more respectful and rule-abiding community.

Streamlined Processes: An in-game UI, even if it’s an iframe of an online CAD, streamlines processes for players, making the roleplay experience smoother and more enjoyable.
In essence, these features can help roleplay communities by fostering a more organized, realistic, and engaging environment for all participants. 😊

### Out of RP or In RP

Both

**Comment by DrMxrcy** [comment]
Would be nice if these were split up into multiple suggestions!

**Comment by Nmiller11126** [comment]
I’ll try to do that tonight

**Comment by DrMxrcy** [comment]
Separated, closing this one out!
