### ISSUE TITLE
/911 Command Resource

### ISSUE THREAD

**Issue by miller622** [CommunityCAD/CommunityCAD#52]
### Type of Suggestion

CAD

### Describe the feature

The way I envision it is a resource that allows you to do /911 in game or something like that and it send a call into the Cad system from the CIV i feel like this would be a great way for stubborn civs who dont leave game while playing

### How would this improve RP

This would improve RP by allowing CIVs to stay in game and be more aware of their surroundings and as well as never breaking RP

### Would this help all communities

I believe this would help many people in getting their civilian players to use the features of the cad more

### Out of RP or In RP

Both

**Comment by gsbarbo** [comment]
If you are talking about the script we already have one here: https://github.com/CommunityCAD/cc-911

**Comment by Nmiller11126** [comment]
Perfect thank you!
