### ISSUE TITLE
Disciplinary System

### ISSUE THREAD

**Issue by miller622** [CommunityCAD/CommunityCAD#57]
### Type of Suggestion

CAD

### Describe the feature

A disciplinary system within the supervisor panel where supervisors can preform and document disciplinary actions, warnings, and sadly even terminations

### How would this improve RP

This would improve the administrative aspect of the departments

### Would this help all communities

Yes this is a administrative feature that helps with organization

### Out of RP or In RP

Outside of RP

**Comment by gsbarbo** [comment]
This is already an option in the Admin menus. See our discord for help: https://discord.com/invite/Sqt2BzUM4F
